authorization = {
  "users" = [
    {
      "nkey" = "UCSA4OXSSIGUSVOJEBVFSNNSVAICFDLCZGVDEW54ZYWMJLYJLIDVXVIL"
    },
    {
      "nkey" = "UCWAVFQZEX7JI4HKOPZNIJSS3AOKLMCUMW4IWKKVP45OXPHJMIMBQVX4"
      "permissions" = {
        "sub" = [
          "agent.0199d917-f810-78a1-8aee-cea066ea7d37"
        ]
        "pub" = [
          "agent.0199d917-f810-78a1-8aee-cea066ea7d37"
        ]
      }
    },
    {
      "nkey" = "UBNU2JCOJCSPVF2FALYK4ZJLKOWOD7TNMWGB5RYZFCSN67T7ZUKHYUI7"
      "permissions" = {
        "sub" = [
          "agent.0199d925-6109-7df3-8fb8-e5e567e24bfa"
        ]
        "pub" = [
          "agent.0199d925-6109-7df3-8fb8-e5e567e24bfa"
        ]
      }
    }
  ]
}
