[package]
name = "core-engine-dto"
version = "0.0.1"
edition = "2024"

[dependencies]
core-engine-db = { workspace = true }
core-engine-const = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
async-nats = { workspace = true }
strum = { workspace = true }
nkeys = { workspace = true }
sled = { workspace = true }
strum_macros = { workspace = true }
