[package]
name = "rs-interactions-center"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "migration"]

[dependencies]
axum = { version = "0.8.6", features = ["json", "multipart", "macros"] }
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["json"] }
serde_json = { version = "1.0.145", features = ["default"] }
sea-orm = { version = "1.1.16", features = ["chrono", "serde_json", "sqlx-postgres", "runtime-tokio", "with-uuid"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
dotenv = "0.15.0"
uuid = { version = "1.18.1", features = ["v4", "v7"] }
serde = { version = "1.0.225", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
async-nats = "0.43.1"
futures-util = "0.3.31"
migration = { path = "migration" }