[package]
name = "core-engine-db-migration"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
name = "CoreEngineDbMigration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
core-engine-consts = { workspace = true }
strum = { workspace = true }
