//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub mark_for_delete: bool,
    #[sea_orm(column_type = "Text")]
    pub nkey_seed: String,
    #[sea_orm(column_type = "Text")]
    pub nkey_pub: String,
    #[sea_orm(unique)]
    pub client_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub nats_jwt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channels_workers::Entity")]
    ChannelsWorkers,
    #[sea_orm(has_many = "super::interactions_channels_assignment::Entity")]
    InteractionsChannelsAssignment,
    #[sea_orm(has_many = "super::queues_channels_assignment::Entity")]
    QueuesChannelsAssignment,
    #[sea_orm(has_many = "super::service_accounts::Entity")]
    ServiceAccounts,
}

impl Related<super::channels_workers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelsWorkers.def()
    }
}

impl Related<super::interactions_channels_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InteractionsChannelsAssignment.def()
    }
}

impl Related<super::queues_channels_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QueuesChannelsAssignment.def()
    }
}

impl Related<super::service_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceAccounts.def()
    }
}

impl Related<super::interactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::interactions_channels_assignment::Relation::Interactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::interactions_channels_assignment::Relation::Channels
                .def()
                .rev(),
        )
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::queues_channels_assignment::Relation::Queues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::queues_channels_assignment::Relation::Channels
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
