//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub state: Uuid,
    pub channel: Uuid,
    pub channel_worker: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::interactions_channels_assignment::Entity")]
    InteractionsChannelsAssignment,
    #[sea_orm(has_many = "super::interactions_skills_assignment::Entity")]
    InteractionsSkillsAssignment,
    #[sea_orm(has_many = "super::runtime_interactions_queues::Entity")]
    RuntimeInteractionsQueues,
}

impl Related<super::interactions_channels_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InteractionsChannelsAssignment.def()
    }
}

impl Related<super::interactions_skills_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InteractionsSkillsAssignment.def()
    }
}

impl Related<super::runtime_interactions_queues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuntimeInteractionsQueues.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        super::interactions_channels_assignment::Relation::Channels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::interactions_channels_assignment::Relation::Interactions
                .def()
                .rev(),
        )
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::runtime_interactions_queues::Relation::Queues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::runtime_interactions_queues::Relation::Interactions
                .def()
                .rev(),
        )
    }
}

impl Related<super::skills::Entity> for Entity {
    fn to() -> RelationDef {
        super::interactions_skills_assignment::Relation::Skills.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::interactions_skills_assignment::Relation::Interactions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
