//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "interactions_channels_assignment")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub interaction_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub channel_id : Uuid , pub created_at : DateTimeWithTimeZone , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::channels::Entity" , from = "Column::ChannelId" , to = "super::channels::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Channels , # [sea_orm (belongs_to = "super::interactions::Entity" , from = "Column::InteractionId" , to = "super::interactions::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Interactions , }

impl Related < super :: channels :: Entity > for Entity { fn to () -> RelationDef { Relation :: Channels . def () } }

impl Related < super :: interactions :: Entity > for Entity { fn to () -> RelationDef { Relation :: Interactions . def () } }

impl ActiveModelBehavior for ActiveModel { }