//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interactions_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub internal_id: i64,
    pub id: Uuid,
    pub r#type: i32,
    pub created_at: DateTimeWithTimeZone,
    pub old_state: Option<Uuid>,
    pub new_state: Option<Uuid>,
    pub queue_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub channel_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
