//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "runtime_users")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , pub state : i32 , pub created_at : DateTimeWithTimeZone , pub state_updated_at : DateTimeWithTimeZone , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::Id" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }