//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "runtime_users_queues")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub queue_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub user_id : Uuid , pub queued_at : DateTimeWithTimeZone , pub on_queue : bool , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::queues::Entity" , from = "Column::QueueId" , to = "super::queues::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Queues , # [sea_orm (belongs_to = "super::users::Entity" , from = "Column::UserId" , to = "super::users::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Users , }

impl Related < super :: queues :: Entity > for Entity { fn to () -> RelationDef { Relation :: Queues . def () } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { Relation :: Users . def () } }

impl ActiveModelBehavior for ActiveModel { }