//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "skills")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , # [sea_orm (column_type = "Text")] pub name : String , pub created_at : DateTimeWithTimeZone , pub parent_id : Uuid , pub mark_for_delete : bool , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::interactions_skills_assignment::Entity")] InteractionsSkillsAssignment , # [sea_orm (belongs_to = "Entity" , from = "Column::ParentId" , to = "Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] SelfRef , # [sea_orm (has_many = "super::skills_groups_assignment::Entity")] SkillsGroupsAssignment , # [sea_orm (has_many = "super::users_skills_assignment::Entity")] UsersSkillsAssignment , }

impl Related < super :: interactions_skills_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: InteractionsSkillsAssignment . def () } }

impl Related < super :: skills_groups_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: SkillsGroupsAssignment . def () } }

impl Related < super :: users_skills_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: UsersSkillsAssignment . def () } }

impl Related < super :: groups :: Entity > for Entity { fn to () -> RelationDef { super :: skills_groups_assignment :: Relation :: Groups . def () } fn via () -> Option < RelationDef > { Some (super :: skills_groups_assignment :: Relation :: Skills . def () . rev ()) } }

impl Related < super :: interactions :: Entity > for Entity { fn to () -> RelationDef { super :: interactions_skills_assignment :: Relation :: Interactions . def () } fn via () -> Option < RelationDef > { Some (super :: interactions_skills_assignment :: Relation :: Skills . def () . rev ()) } }

impl Related < super :: users :: Entity > for Entity { fn to () -> RelationDef { super :: users_skills_assignment :: Relation :: Users . def () } fn via () -> Option < RelationDef > { Some (super :: users_skills_assignment :: Relation :: Skills . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }