//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "skills_groups_assignment")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub skill_id : Uuid , # [sea_orm (primary_key , auto_increment = false)] pub group_id : Uuid , pub created_at : DateTimeWithTimeZone , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::groups::Entity" , from = "Column::GroupId" , to = "super::groups::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Groups , # [sea_orm (belongs_to = "super::skills::Entity" , from = "Column::SkillId" , to = "super::skills::Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] Skills , }

impl Related < super :: groups :: Entity > for Entity { fn to () -> RelationDef { Relation :: Groups . def () } }

impl Related < super :: skills :: Entity > for Entity { fn to () -> RelationDef { Relation :: Skills . def () } }

impl ActiveModelBehavior for ActiveModel { }