//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "user_states")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : i32 , # [sea_orm (column_type = "Text" , unique)] pub name : String , # [sea_orm (column_type = "Text" , nullable)] pub description : Option < String > , pub parent_id : Option < i32 > , pub mark_for_delete : bool , pub system_state : bool , pub user_control_allowed : bool , pub created_at : DateTimeWithTimeZone , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "Entity" , from = "Column::ParentId" , to = "Column::Id" , on_update = "NoAction" , on_delete = "Cascade" ,)] SelfRef , }

impl ActiveModelBehavior for ActiveModel { }