//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "users")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub id : Uuid , # [sea_orm (column_type = "Text")] pub username : String , # [sea_orm (column_type = "Text" , unique)] pub name : String , # [sea_orm (column_type = "Text" , unique)] pub nkey_seed : String , # [sea_orm (column_type = "Text" , unique)] pub nkey_pub : String , pub service_account : bool , pub created_at : DateTimeWithTimeZone , pub mark_for_delete : bool , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::interactions_events::Entity")] InteractionsEvents , # [sea_orm (has_one = "super::runtime_users::Entity")] RuntimeUsers , # [sea_orm (has_many = "super::runtime_users_queues::Entity")] RuntimeUsersQueues , # [sea_orm (has_many = "super::users_groups_assignment::Entity")] UsersGroupsAssignment , # [sea_orm (has_many = "super::users_queues_assignment::Entity")] UsersQueuesAssignment , # [sea_orm (has_many = "super::users_skills_assignment::Entity")] UsersSkillsAssignment , }

impl Related < super :: interactions_events :: Entity > for Entity { fn to () -> RelationDef { Relation :: InteractionsEvents . def () } }

impl Related < super :: runtime_users :: Entity > for Entity { fn to () -> RelationDef { Relation :: RuntimeUsers . def () } }

impl Related < super :: runtime_users_queues :: Entity > for Entity { fn to () -> RelationDef { Relation :: RuntimeUsersQueues . def () } }

impl Related < super :: users_groups_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: UsersGroupsAssignment . def () } }

impl Related < super :: users_queues_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: UsersQueuesAssignment . def () } }

impl Related < super :: users_skills_assignment :: Entity > for Entity { fn to () -> RelationDef { Relation :: UsersSkillsAssignment . def () } }

impl Related < super :: groups :: Entity > for Entity { fn to () -> RelationDef { super :: users_groups_assignment :: Relation :: Groups . def () } fn via () -> Option < RelationDef > { Some (super :: users_groups_assignment :: Relation :: Users . def () . rev ()) } }

impl Related < super :: skills :: Entity > for Entity { fn to () -> RelationDef { super :: users_skills_assignment :: Relation :: Skills . def () } fn via () -> Option < RelationDef > { Some (super :: users_skills_assignment :: Relation :: Users . def () . rev ()) } }

impl ActiveModelBehavior for ActiveModel { }