[package]
name = "core-voice"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = { workspace = true }
core-engine-dto = { workspace = true }
async-nats = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dotenv = { workspace = true }
uuid = { workspace = true }
futures-util = { workspace = true }
