pub const DEFAULT_QUEUE_PRIORITY: i32 = 50;

pub const NATS_OPERATOR_SEED_CONFIG_KEY: &str = "NATS_OPERATOR_SEED";
pub const NATS_OPERATOR_JWT_CONFIG_KEY: &str = "NATS_OPERATOR_JWT";

pub const NATS_SYS_SEED_CONFIG_KEY: &str = "NATS_SYS_SEED";
pub const NATS_SYS_JWT_CONFIG_KEY: &str = "NATS_SYS_JWT";

pub const NATS_CORE_ENGINE_SEED_CONFIG_KEY: &str = "NATS_CORE_ENGINE_SEED";
pub const NATS_CORE_ENGINE_JWT_CONFIG_KEY: &str = "NATS_CORE_ENGINE_JWT";

pub const NATS_DEFAULT_SEED_CONFIG_KEY: &str = "NATS_DEFAULT_SEED";
pub const NATS_DEFAULT_JWT_CONFIG_KEY: &str = "NATS_DEFAULT_JWT";
