[package]
name = "core-engine-db"
version = "0.0.1"
edition = "2024"

[dependencies]
uuid = { workspace = true }
tracing = { workspace = true }
core-engine-const = { workspace = true }
strum = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
tokio = { workspace = true }
