//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "core", table_name = "config_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::config_queues_to_channels_map::Entity")]
    ConfigQueuesToChannelsMap,
}

impl Related<super::config_queues_to_channels_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigQueuesToChannelsMap.def()
    }
}

impl Related<super::config_queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::config_queues_to_channels_map::Relation::ConfigQueues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::config_queues_to_channels_map::Relation::ConfigChannels
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
