//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub mark_for_delete: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::queues_groups_assignment::Entity")]
    QueuesGroupsAssignment,
    #[sea_orm(has_many = "super::skills_groups_assignment::Entity")]
    SkillsGroupsAssignment,
    #[sea_orm(has_many = "super::users_groups_assignment::Entity")]
    UsersGroupsAssignment,
}

impl Related<super::queues_groups_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QueuesGroupsAssignment.def()
    }
}

impl Related<super::skills_groups_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkillsGroupsAssignment.def()
    }
}

impl Related<super::users_groups_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersGroupsAssignment.def()
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::queues_groups_assignment::Relation::Queues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::queues_groups_assignment::Relation::Groups
                .def()
                .rev(),
        )
    }
}

impl Related<super::skills::Entity> for Entity {
    fn to() -> RelationDef {
        super::skills_groups_assignment::Relation::Skills.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::skills_groups_assignment::Relation::Groups
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_groups_assignment::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_groups_assignment::Relation::Groups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
