//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "interactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub state: i32,
    pub channel_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Channels,
    #[sea_orm(has_many = "super::interactions_skills_assignment::Entity")]
    InteractionsSkillsAssignment,
    #[sea_orm(has_many = "super::runtime_interactions_queues::Entity")]
    RuntimeInteractionsQueues,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::interactions_skills_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InteractionsSkillsAssignment.def()
    }
}

impl Related<super::runtime_interactions_queues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuntimeInteractionsQueues.def()
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::runtime_interactions_queues::Relation::Queues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::runtime_interactions_queues::Relation::Interactions
                .def()
                .rev(),
        )
    }
}

impl Related<super::skills::Entity> for Entity {
    fn to() -> RelationDef {
        super::interactions_skills_assignment::Relation::Skills.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::interactions_skills_assignment::Relation::Interactions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
