//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "core", table_name = "interactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub internal_id: i64,
    pub id: Uuid,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::runtime_interaction_to_skills_map::Entity")]
    RuntimeInteractionToSkillsMap,
}

impl Related<super::runtime_interaction_to_skills_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuntimeInteractionToSkillsMap.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
