//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod channels;
pub mod groups;
pub mod interaction_states;
pub mod interactions;
pub mod interactions_skills_assignment;
pub mod queues;
pub mod queues_channels_assignment;
pub mod queues_groups_assignment;
pub mod runtime_interactions_queues;
pub mod runtime_users;
pub mod runtime_users_queues;
pub mod skills;
pub mod skills_groups_assignment;
pub mod user_states;
pub mod users;
pub mod users_groups_assignment;
pub mod users_queues_assignments;
pub mod users_skills_assignment;
