//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod config_channels;
pub mod config_queues;
pub mod config_queues_to_channels_map;
pub mod interactions;
pub mod runtime_interactions_queues;
