//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "core", table_name = "queues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::queues_channels_assignment::Entity")]
    QueuesChannelsAssignment,
    #[sea_orm(has_many = "super::queues_groups_assignment::Entity")]
    QueuesGroupsAssignment,
    #[sea_orm(has_many = "super::runtime_interactions_queues::Entity")]
    RuntimeInteractionsQueues,
}

impl Related<super::queues_channels_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QueuesChannelsAssignment.def()
    }
}

impl Related<super::queues_groups_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QueuesGroupsAssignment.def()
    }
}

impl Related<super::runtime_interactions_queues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuntimeInteractionsQueues.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        super::queues_channels_assignment::Relation::Channels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::queues_channels_assignment::Relation::Queues
                .def()
                .rev(),
        )
    }
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::queues_groups_assignment::Relation::Groups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::queues_groups_assignment::Relation::Queues
                .def()
                .rev(),
        )
    }
}

impl Related<super::interactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::runtime_interactions_queues::Relation::Interactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::runtime_interactions_queues::Relation::Queues
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
