//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "runtime_interactions_queues")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub queue_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub interaction_id: Uuid,
    pub priority: i32,
    pub queued_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::interactions::Entity",
        from = "Column::InteractionId",
        to = "super::interactions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Interactions,
    #[sea_orm(
        belongs_to = "super::queues::Entity",
        from = "Column::QueueId",
        to = "super::queues::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Queues,
}

impl Related<super::interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Interactions.def()
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Queues.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
