//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "core", table_name = "runtime_interactions_queues")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub internal_id: i64,
    #[sea_orm(unique)]
    pub interaction_internal_id: i64,
    pub queue_internal_id: i64,
    pub queued_at: DateTime,
    pub priority: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
