//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "core", table_name = "runtime_interaction_to_skills_map")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub internal_id: i64,
    pub interaction_internal_id: i64,
    pub skill_internal_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::config_skills::Entity",
        from = "Column::SkillInternalId",
        to = "super::config_skills::Column::InternalId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ConfigSkills,
    #[sea_orm(
        belongs_to = "super::interactions::Entity",
        from = "Column::InteractionInternalId",
        to = "super::interactions::Column::InternalId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Interactions,
}

impl Related<super::config_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigSkills.def()
    }
}

impl Related<super::interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Interactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
