//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_states")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub parent_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::runtime_users::Entity")]
    RuntimeUsers,
}

impl Related<super::runtime_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuntimeUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
