listen: "0.0.0.0:4222"

debug: true
trace: false
logtime: true

websocket {
    listen: "0.0.0.0:4223"
    no_tls: true
    same_origin: false
}


authorization {
  auth_callout {
    # HTTP endpoint for verifying JWTs
    url: "http://localhost:8080/verify-jwt"

    # Optional timeout for the callout (in milliseconds)
    timeout: 2000

    # Optional custom headers sent with the callout
    headers {
      "X-Auth-Source": "nats-server"
    }

    # When true, allows permissions to be returned from the auth callout
    # Example: publish/subscribe permissions can be set dynamically
    allow_auth_user_override: true
  }
}

# Optional limits for safety
max_connections: 1000
ping_interval: 2m
ping_max: 5
